/**
 *
 * @author Pratik
 */
package controller;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import model.League;
import java.util.List;
import java.util.LinkedList;
import java.util.Iterator;


public class ListLeaguesServlet extends HttpServlet {
    
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
            /* This servlet responds to an HTTP GET request method. Therefore it must override doGet method. */
        
//        List leaguelist = new LinkedList();
//        leaguelist.add(new League(2003, "Spring", "Soccer League(Spring '03)"));
//        leaguelist.add(new League(2003, "Summer", "Soccer League(Spring '03)"));
//        leaguelist.add(new League(2003, "Fall", "Soccer League(Spring '03)"));
//        leaguelist.add(new League(2004, "Spring", "Soccer League(Spring '04)"));
//        leaguelist.add(new League(2004, "Summer", "Soccer League(Spring '04)"));
//        leaguelist.add(new League(2004, "Fall", "Soccer League(Spring '04)"));
        
        //Set page title
        String pagetitle = "Duke Soccer League: list leagues";
        
        //Retrieve the list of leagues  from the context attribute.
        ServletContext context = getServletContext();
        List leaguelist = (List) context.getAttribute("leaguelist");
        
        //Specify the content type as HTML
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        /* You must set the content type to match the MIME type of the content being generated.Here HTML
         * is being generated by the servlet.
         */
        
        out.println("<html>");
        out.println("<head>");
        out.println("<title>"+pagetitle+"</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<p>The list of leagues are:</p>");
        out.println("<ul>");
        
        /* The dynamic list for league titles are generated. Because the list of leagues are represented by a List
         * object, the loop uses an Iterator object.
         */
        Iterator items = leaguelist.iterator();
        while(items.hasNext()){
            League league = (League)items.next();
            out.println("<li>"+league.getTitle()+"</li>");
        }
        
        out.println("</ul></body></html>");
    }
    }